import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'app-input-button-unit',
  standalone: true,
  imports: [CommonModule],
  template: `
  <p>
    input-button-unit works!
    The item title is: {{ title }}
  </p>
  <input [value]="generateTitle()">

  {{ generateTitle() }}
  <button>Save</button>
`,
  styleUrls: ['./input-button-unit.component.css']
})
export class InputButtonUnitComponent {
  title = 'Hello World';

  constructor() {
    setTimeout(() => {
    this.title = 'This is not the title you are looking for';
  }, 3000);
  }

  generateTitle(): string {
  return 'This title was generated by a method.';
}
}

